services:
  video-converter:
    image: jrottenberg/ffmpeg:8-scratch
    container_name: vid_processor
    volumes:
      - /srv/storage:/media:rw
    user: "1000:1000" # Run as 'ubuntu' user to avoid permission issues
    restart: always
    entrypoint: /bin/sh
    command: >
      -c "while true; do
        for f in /media/video_in/*; do
          [ -f \"$$f\" ] || continue;

          case \"$$f\" in
            *.mp4|*.mkv|*.avi|*.mov|*.flv|*.webm) ;;
            *) continue ;;
          esac

          filename=\"$$(basename \"$$f\")\";
          name=\"$${filename%.*}\";
          out=\"/media/video_out/$$name.mov\";

          echo \"Processing $$f -> $$out\";
          ffmpeg -i \"$$f\" -c:v libx264 -preset fast -c:a aac \"$$out\" && rm \"$$f\";
        done;
        sleep 10;
      done"