---
# tasks file for setup_nas
- name: Configure Samba and Tailscale
  # hosts: web_servers
  become: true
  block:
    - name: Install Samba
      apt:
        name: samba
        state: present
        update_cache: yes
      register: samba_install
    - name: Create Samba config directory if missing
      file:
        path: /etc/samba
        state: directory
        mode: '0755'
    - name: Ensure smb.conf exists
      copy:
        content: ""
        dest: /etc/samba/smb.conf
        force: no  # Only creates it if it's actually missing
    - name: Configure Samba Share
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [DevOpsShare]
             comment = Persistent Lab Storage
             path = /srv/storage
             read only = no
             browsable = yes
             guest ok = yes
             force user = ubuntu

    - name: Restart Samba
      service:
        name: smbd
        state: restarted

    - name: Install Tailscale
      shell: "curl -fsSL https://tailscale.com/install.sh | sh"
      args:
        creates: /usr/bin/tailscale

    - name: Bring Tailscale Up using OAuth
      command: >
        tailscale up 
        --authkey="tskey-client-{{ ts_client_id }}-{{ ts_client_secret }}"
        --hostname="devops-lab-vm"
      # no_log is CRITICAL so your secret doesn't leak in the terminal output
      no_log: true