# ansible-playbook setup.yml -u ubuntu --become --ask-vault-pass
---
# tasks file for setup_nas
- name: Include vault variables first
  include_vars: secrets.yml
- name: Configure Samba and Tailscale
  # hosts: web_servers
  become: true
  become_user: root
  block:
    - name: Install Samba
      apt:
        name: samba
        state: present
        update_cache: yes
        # cache_valid_time: 0  # Force cache update
    - name: Configure Samba Share
      ansible.builtin.blockinfile:
        path: /etc/samba/smb.conf
        # create: yes
        block: |
          [DevOpsShare]
             comment = Persistent Lab Storage
             path = /srv/storage
             read only = no
             browsable = yes
             guest ok = yes
             force user = ubuntu
    - name: Verify file content immediately
      ansible.builtin.shell: "cat /etc/samba/smb.conf | tail -8" 
      register: smb_content
    - name: Show the content Ansible sees
      ansible.builtin.debug:
        var: smb_content.stdout_lines
    - name: Restart Samba
      service:
        name: smbd
        state: restarted

    - name: Install Tailscale
      shell: "curl -fsSL https://tailscale.com/install.sh | sh"
      args:
        creates: /usr/bin/tailscale

    - name: Bring Tailscale Up using OAuth
      command: >
        tailscale up --auth-key='{{vault_ts_client_secret}}?ephemeral=false&preauthorized=true' --advertise-tags=tag:tds
        --hostname="devops-lab"
      # no_log is CRITICAL so your secret doesn't leak in the terminal output
      no_log: true