services:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9443:9443"
    deploy:
      placement:
        constraints: [node.role == manager]

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"
    deploy:
      mode: global # Runs on every node to collect all logs

  homepage:
    image: ghcr.io/gethomepage/homepage:dev
    ports:
      - "3000:3000"
    volumes:
      - /srv/storage/config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  portainer_data: